# Use any base image you'd like here, this is a private one
FROM ***.dkr.ecr.eu-west-1.amazonaws.com/mxnet-gluonts-training-0.3.3-cpu:latest

COPY src/ /opt/program
COPY conf/ /opt/program
COPY container/requirements_train.txt /opt/program

RUN pip install -r requirements_train.txt

ENV SM_DATA_DIR /opt/ml/input/data
ENV SM_CHANNEL_TRAIN /opt/ml/input/data/training
ENV SM_CHANNEL_TEST /opt/ml/input/data/testing
ENV SM_MODEL_DIR /opt/ml/model

ENTRYPOINT ["python"]