global:
    tags:
        project: ***
        algorithm: mlp
        environment: dev
    role_arn: arn:aws:iam::***:role/***
    security_group_ids: sg-***
    subnets: subnet-***, subnet-***
    volume_size_in_gb: 10
    
train:
    bucket_input: ***
    bucket_output: ***
    instance_type: ml.c5.4xlarge
    instance_count: 1
    max_run_time: 86400 # seconds
    hyperparameters:
        context_length: 140
        num_hidden_dimensions': 5
        len_hidden_dimensions': 38
        epochs: 200
        batch_size: 512
        num_batches_per_epoch: 217
        learning_rate: 5e-05